# Firefly ECM DocuSign Adapter Configuration
# This file provides example configuration for the DocuSign eSignature adapter

# ECM eSignature Provider Configuration
firefly:
  ecm:
    esignature:
      provider: docusign
    adapter:
      docusign:
        # Required DocuSign Configuration
        integration-key: ${DOCUSIGN_INTEGRATION_KEY}
        user-id: ${DOCUSIGN_USER_ID}
        account-id: ${DOCUSIGN_ACCOUNT_ID}
        private-key: ${DOCUSIGN_PRIVATE_KEY}
        
        # Optional DocuSign Configuration
        base-url: ${DOCUSIGN_BASE_URL:https://na3.docusign.net/restapi}
        auth-server: ${DOCUSIGN_AUTH_SERVER:https://account.docusign.com}
        sandbox-mode: ${DOCUSIGN_SANDBOX_MODE:false}
        
        # Webhook Configuration (Optional)
        webhook-url: ${DOCUSIGN_WEBHOOK_URL:}
        webhook-secret: ${DOCUSIGN_WEBHOOK_SECRET:}
        
        # Connection and Performance Settings
        connection-timeout: ${DOCUSIGN_CONNECTION_TIMEOUT:PT30S}
        read-timeout: ${DOCUSIGN_READ_TIMEOUT:PT60S}
        max-retries: ${DOCUSIGN_MAX_RETRIES:3}
        
        # JWT Authentication Settings
        jwt-expiration: ${DOCUSIGN_JWT_EXPIRATION:3600}
        
        # Envelope Management Settings
        enable-polling: ${DOCUSIGN_ENABLE_POLLING:true}
        polling-interval: ${DOCUSIGN_POLLING_INTERVAL:PT5M}
        
        # Default Email Templates
        default-email-subject: ${DOCUSIGN_DEFAULT_EMAIL_SUBJECT:Please sign this document}
        default-email-message: ${DOCUSIGN_DEFAULT_EMAIL_MESSAGE:Please review and sign the attached document(s).}
        
        # Embedded Signing Configuration
        enable-embedded-signing: ${DOCUSIGN_ENABLE_EMBEDDED_SIGNING:false}
        return-url: ${DOCUSIGN_RETURN_URL:}
        
        # Document Retention Settings
        enable-retention: ${DOCUSIGN_ENABLE_RETENTION:true}
        retention-days: ${DOCUSIGN_RETENTION_DAYS:2555}

# Logging Configuration for DocuSign Adapter
logging:
  level:
    com.firefly.ecm.adapter.docusign: INFO
    com.docusign.esign: WARN
